### ISSUE TITLE
Utility function for getting error code

### ISSUE THREAD

**Issue by calufornia** [workos/workos-go#151]
I notice that there's a [function](https://github.com/workos/workos-go/blob/main/pkg/workos_errors/errors.go) for determining if an error is a 400, but I've encountered errors where the HTTP status code is 422, for example when an email is malformed. It would be great if there were a utility method that could return the status code of a workos `HTTPError` - right now I'm just looking at the prefix of the error message and seeing if it start with 422.

An alternative is to expose the [HTTPError struct](https://github.com/workos/workos-go/blob/main/pkg/workos_errors/errors.go) so that the client can perform a type assertion.

**Comment by brunocalogero** [comment]
Hey @calufornia, this has been addressed and merged very recently by one of my team-mates :) https://github.com/workos/workos-go/pull/152

The HTTPError struct is exposed

**Comment by mthadley** [comment]
As @brunocalogero pointed out, the `HTTPError` struct is now public, so this should hopefully allow you to introspect on the particular error code.

I'l close this for now, but if you hit any more issues, feel free to open a new issue. Thanks!
