### ISSUE TITLE
LogStreams

### ISSUE THREAD

**Issue by weaverjess** [workos/workos-go#202]
It appears that LogStreams is not available in the GoSDK yet. Is this being looked into?

**Comment by jonatascastro12** [comment]
Hey @weaverjess !

I can confirm that LogStreams is indeed available in the Go SDK. Check this line: https://github.com/workos/workos-go/blob/ec9e683bba39ec3b05abc7376c633929fc98376f/pkg/portal/client.go#L69

In case you were searching for a different feature, I want to clarify that generating portal links with the `log_streams` intent is the only Log Streams feature supported by WorkOS API. Once you generate a link, IT Admins can use it to set up a Log Stream or you can also set up Log Stream from the WorkOS dashboard.

You can also check the example from the docs: https://workos.com/docs/audit-logs/log-streams
