### ISSUE TITLE
Failing to marshal JWK returned from `usermanagement.GetJWKSURL`

### ISSUE THREAD

**Issue by ibrahimbutt** [workos/workos-go#316]
Using `usermanagement.GetJWKSURL`, I am given the URL from where I can fetch JWKs to verify a JWT. To do the latter, I am using (or intend to use):

- [github.com/golang-jwt/jwt/v5](github.com/golang-jwt/jwt/v5)
- [github.com/MicahParks/keyfunc/v3](github.com/MicahParks/keyfunc/v3)

This is a common combination. Below is the recommended approach to setup `keyfunk`:

```go
usermanagement.SetAPIKey(cfg.WorkOS.APIKey)
jwksUrl, _ := usermanagement.GetJWKSURL(cfg.WorkOS.ClientID)

k, _ := keyfunc.NewDefault([]string{jwksUrl.String()})

// Error handling removed for example brevity
```

For now, I am expecting my application to start before writing any logic to verify JWTs, however, the last line gives the following error:
```
 http.go:98: ERROR Failed to refresh HTTP JWK Set from remote HTTP resource. error="failed to create JWK from JWK Marshal: failed to validate JSON Web Key: failed to validate JWK: X5TS256 in marshal does not match X5TS256 in marshalled" url=https://api.workos.com/sso/jwks/<CLIENT_ID>
```

I'm unfamilliar with JWKs. Is this a problem with the WorkOS implementation of a JWK, or possibly the library I am using? Any insight would be appreciated.

Edit: While I am here, I've also noticed that the decoded JWT does not have the `role` property in it.

**Comment by PaulAsjes** [comment]
Hey there, we're looking into this and will get back to you shortly.

**Comment by PaulAsjes** [comment]
Hi again @ibrahimbutt, I'm not sure why you're getting that error, but I was able to get this to work using the following JWT libraries:
* github.com/golang-jwt/jwt
* github.com/lestrrat-go/jwx/jwk

Here's my code if you want to try for yourself:

```golang
package main

import (
	"context"
	"fmt"

	"github.com/golang-jwt/jwt"
	"github.com/lestrrat-go/jwx/jwk"

	"github.com/workos/workos-go/v4/pkg/usermanagement"
)

func main() {
	usermanagement.SetAPIKey("sk_test_<your key here>")
	jwksUrl, _ := usermanagement.GetJWKSURL("client_<your client ID here>")

	fmt.Println(jwksUrl)

	tokenString := "<insert access token here>"

	set, err := jwk.Fetch(context.Background(), jwksUrl.String())
	if err != nil {
		fmt.Printf("Failed to fetch JWKS: %s\n", err)
		return
	}

	// Parse the token
	token, err := jwt.Parse(tokenString, func(token *jwt.Token) (interface{}, error) {
		// Check the signing method
		if _, ok := token.Method.(*jwt.SigningMethodRSA); !ok {
			return nil, fmt.Errorf("Unexpected signing method: %v", token.Header["alg"])
		}

		// Get the key ID from the token header
		kid, ok := token.Header["kid"].(string)
		if !ok {
			return nil, fmt.Errorf("kid header not found")
		}

		// Find the key in the JWKS
		keys, _ := set.LookupKeyID(kid)

		// Get the first key
		var key interface{}
		err = keys.Raw(&key)
		if err != nil {
			return nil, err
		}

		// Return the public key
		return key, nil
	})

	if err != nil {
		fmt.Printf("Failed to parse token: %s\n", err)
		return
	}

	// Check if token is valid
	if claims, ok := token.Claims.(jwt.MapClaims); ok && token.Valid {
		fmt.Printf("Token is valid: %v\n", claims)
	} else {
		fmt.Println("Invalid token")
	}
}
```
This returned the following for me (redacted some values):
```
Token is valid: map[exp:1.71139899e+09 iat:1.71139869e+09 iss:https://api.workos.com jti:123 org_id:org_123 role:member sid:session_123 sub:user_123]
```

Note that `role:member` is present here.

Let me know if that works for you!

**Comment by PaulAsjes** [comment]
Closing this for now as it seems to be resolved. Feel free to reopen if you're still having difficulties.

**Comment by MicahParks** [comment]
@ibrahimbutt that error was received because the `github.com/MicahParks/jwkset` project calculated a different certificate thumbprint than what was presented in the JWK Set hosted by WorkOS.

I believe the thumbprint calculated by the `jwkset` project is correct, since it [appears to match with what OpenSSL calculates](https://github.com/MicahParks/jwkset/issues/32#issuecomment-2133924166). I opened a support ticket with WorkOS and they have identified the issue and are working on a fix now.

The `keyfunc` project will be updated in the future to more conveniently allow JWK Set validation skipping. It's possible today, but requires package users to understand both the `keyfunc` and `jwkset` projects. Since `keyfunc` is a convenience wrapper, I'll be attempting to make it more convenient for cases such as this. See the tracking issue linked below:
https://github.com/MicahParks/keyfunc/issues/126

**Comment by MicahParks** [comment]
@ibrahimbutt WorkOS responded to the ticket and said they deployed a fix. Would you test again?

**Comment by ibrahimbutt** [comment]
@PaulAsjes trying something new here. Are you hiring? I have 5-6 years of experience in FinTech using Java and Spring Boot (API Design and Development).

**Comment by ibrahimbutt** [comment]
@MicahParks I would've been more than happy to test it out, however I do not have access to the codebase anymore.
